stages:
  - build
  - deploy

.only_changes: &changes_def
    changes:
      - Dockerfile
      - Makefile
      - tests/**/*   

# ===================== 
# Variables may be: 
# - release (buster only) 
# - nightly-release (buster only) 
# - ltr 
# - nightly-ltr 
# ====================== 

.build:
  stage: build
  script:
    - make build test deliver clean FLAVOR=$QGIS_FLAVOR
    - $FACTORY_SCRIPTS/push-to-docker-hub.sh
  environment:
    name: snap
  artifacts:
    paths:
      - factory.manifest
  only:
    <<: *changes_def
    refs:
      - schedules
  tags:
    - infrav3

build:ltr:
  extends: .build
  variables:
    QGIS_FLAVOR: release
  only:
    variables:
      - $BUILDTYPE== "releases"

build:nightly-ltr:
  extends: .build
  variables:
    QGIS_FLAVOR: nightly-release
  only:
    variables:
      - $BUILDTYPE== "nightlies"

# XXX Do no trigger jobs in this branch because triggers
# occurs already in the master branch
#  script:
#    - $FACTORY_SCRIPTS/trigger-ci $PY_QGIS_SERVER_ID $PY_QGIS_SERVER_TOKEN master
#    - $FACTORY_SCRIPTS/trigger-ci $PY_QGIS_WPS_ID $PY_QGIS_WPS_TOKEN master
#  only:
#    variables:
#        - $BUILDTYPE== "releases"

