stages:
  - build
  - deploy


# ===================== 
# Variables may be: 
# - release
# - nightly-release
# - ltr 
# - nightly-ltr 
# ====================== 

.build:
  stage: build
  script:
    - make build test deliver clean FLAVOR=$QGIS_FLAVOR
    - $FACTORY_SCRIPTS/push-to-docker-hub.sh
  environment:
    name: snap
  artifacts:
    paths:
      - factory.manifest
  only:
    refs:
      - schedules
  tags:
    - infrav3

build:ltr:
  extends: .build
  variables:
    QGIS_FLAVOR: ltr
  only:
    variables:
      - $BUILDTYPE == "releases"

build:release:
  extends: .build
  variables:
    QGIS_FLAVOR: release
  only:
    variables:
      - $BUILDTYPE == "releases"

build:nightly-ltr:
  extends: .build
  variables:
    QGIS_FLAVOR: nightly-ltr
  only:
    variables:
      - $BUILDTYPE == "nightlies"

build:nightly-release:
  extends: .build
  variables:
    QGIS_FLAVOR: nightly-release
  only:
    variables:
      - $BUILDTYPE == "nightlies"

deploy:
  stage: deploy
  script:
    - $FACTORY_SCRIPTS/trigger-ci $PY_QGIS_SERVER_ID $PY_QGIS_SERVER_TOKEN master
    - $FACTORY_SCRIPTS/trigger-ci $PY_QGIS_SERVER_ID $PY_QGIS_SERVER_TOKEN 1.5.x 
    - $FACTORY_SCRIPTS/trigger-ci $PY_QGIS_WPS_ID $PY_QGIS_WPS_TOKEN master
    - $FACTORY_SCRIPTS/trigger-ci $PY_QGIS_WPS_ID $PY_QGIS_WPS_TOKEN 1.5.x
  only:
    variables:
      - $BUILDTYPE == "releases"
  tags:
    - infrav3-plain


